- name: set fact _vhosts
  set_fact:
    _vhosts: "{{ _vhosts + [_vhost] }}"
  vars:
    _vhost:
      name: '{{ item.name }}'
      server_name: '{{ item.server_name }}'
      server_alias: "{{ item.server_alias|default([]) }}"
      http_port: "{{ item.http_port|default(80) }}"
      https_port: "{{ item.https_port|default(443) }}"
      config: "{{ item.config|default('') }}"
  loop: '{{ webserver_vhosts }}'
  loop_control:
    label: "{{ item.name }}"

- name: debug _vhosts
  debug:
    msg: "{{ _vhosts }}"

- name: create vhosts
  template:
    src: "nginx/sites/vhost.conf.j2"
    dest: '/etc/nginx/sites-available/{{ vhost.name }}.conf'
  notify: reload nginx
  loop: '{{ _vhosts }}'
  loop_control:
    loop_var: vhost
    label: "{{ vhost.name }}"

- name: enable vhosts
  file:
    src: '../sites-available/{{ vhost.name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ vhost.name }}.conf'
    state: link
  notify: reload nginx
  loop: '{{ _vhosts }}'
  loop_control:
    loop_var: vhost
    label: "{{ vhost.name }}"
