- name: 'database create instances'
  mysql_db:
    name: "{{ instance.name }}"
    state: present
  delegate_to: "{{ instance.delegate }}"
  loop: "{{ _databases }}"
  loop_control:
    loop_var: instance
    label: "{{ instance | combine({'password': 'redacted'}) }}"

- name: 'database create users'
  mysql_user:
    name: "{{ instance.user }}"
    password: "{{ instance.password }}"
    priv: "{{ instance.name }}.*:ALL"
    host: "{{ ansible_fqdn }}"
    state: present
  delegate_to: "{{ instance.delegate }}"
  loop: "{{ _databases }}"
  loop_control:
    loop_var: instance
    label: "{{ instance | combine({'password': 'redacted'}) }}"

- name: deploy db parameters file
  template:
    src: website/db/database.yml.j2
    dest: '{{ vhost.home_path }}/{{ vhost.name }}/private/database.yml'
    owner: root
    group: '{{ vhost.name }}'
    mode: '0640'
  diff: no
  loop: "{{ _vhosts | selectattr('website.db', 'equalto', True) | selectattr('name', 'in', _vhostfilter) | list }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.home_path }}/{{ vhost.name }}/private/database.yml"
