- name: 'database create instances'
  community.mysql.mysql_db:
    name: "{{ instance.name }}"
    state: present
  delegate_to: "{{ instance.delegate }}"
  loop: "{{ _databases }}"
  loop_control:
    loop_var: instance
    label: "{{ instance | combine({'password': 'redacted'}) }}"

- name: include db instance create users
  include_tasks: website/db_instance_create_users.yml
  vars:
    _db_grant_host: "{{ ansible_fqdn }}"

- name: include db instance create users for additional host grants
  include_tasks: website/db_instance_create_users.yml
  vars:
    _db_grant_host: "{{ item }}"
  loop: '{{ webserver_db_grant_additional_hosts }}'
  when: webserver_db_grant_additional_hosts | length > 0

- name: deploy db parameters file
  template:
    src: website/db/database.yml.j2
    dest: '{{ vhost.home_path }}/{{ vhost.name }}/private/database.yml'
    owner: root
    group: '{{ vhost.name }}'
    mode: '0640'
  diff: no
  loop: "{{ _vhosts | selectattr('website.db', 'equalto', True) | selectattr('name', 'in', _vhostfilter) | list }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.home_path }}/{{ vhost.name }}/private/database.yml"
