- name: 'database {{ instance.db.name }} create instance'
  mysql_db:
    name: "{{ instance.db.name }}"
    state: present
  delegate_to: "{{ instance.db.delegate }}"

- name: 'database {{ instance.db.name }} create user {{ instance.db.user }}'
  mysql_user:
    name: "{{ instance.db.user }}"
    password: "{{ instance.db.password }}"
    priv: "{{ instance.db.name }}.*:ALL"
    host: "{{ ansible_fqdn }}"
    state: present
  delegate_to: "{{ instance.db.delegate }}"
