- name: wordpress download wp-cli binary
  get_url:
    url: "https://github.com/wp-cli/wp-cli/releases/download/v{{ webserver_website_wordpress_cli_version }}/wp-cli-{{ webserver_website_wordpress_cli_version }}.phar"
    dest: /usr/local/bin/wp
    mode: 0755
  ignore_errors: yes  # noqa ignore-errors

- name: install wp-cli dependencies
  package:
    pkg: mariadb-client

- name: ensure wordpress-updater log folder exists
  file:
    path: /var/log/wordpress-updater
    state: directory
    owner: root
    group: adm
    mode: 0755

- name: deploy wordpress-updater logrotate config
  template:
    src: website/wordpress/logrotate-wordpress-updater.j2
    dest: /etc/logrotate.d/wordpress-updater
    owner: root
    group: root
    mode: 0644

- name: wordpress deploy updater cronjob
  template:
    src: website/wordpress/wordpress-updater.j2
    dest: /etc/cron.daily/wordpress-updater
    owner: root
    group: root
    mode: 0700
  vars:
    wordpress_instances: "{{ _vhosts | selectattr('website.type', 'equalto', 'wordpress') | list }}"
  when: webserver_website_wordpress_cronjob

- name: include vhosts with wordpress instance
  include_tasks: wordpress_instance.yml
  loop: "{{ _vhosts | selectattr('website.type', 'equalto', 'wordpress') | selectattr('name', 'in', _vhostfilter) | list }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"
