- name: tags-block
  tags: webserver
  block:

  - name: tags-block
    tags: webserver_apache2
    block:

    - name: include apache2
      include_tasks: apache2/main.yml
      when: include_webserver_apache2
      tags:
        - webserver_tmp_vhost_debug_set_fact_performance
        - webserver_tmp_vhost_debug_create_vhosts

  - name: tags-block
    tags: webserver_nginx
    block:

    - name: include nginx
      include_tasks: nginx/main.yml
      when: include_webserver_nginx

  - name: tags-block
    tags: webserver_stats
    block:

    - name: include stats
      include_tasks: stats/main.yml
      when: include_webserver_stats and (include_webserver_apache2 or include_webserver_nginx)

  - name: tags-block
    tags: webserver_letsencrypt
    block:

    - name: include letsencrypt
      include_tasks: letsencrypt/main.yml
      when: include_webserver_letsencrypt

  - name: tags-block
    tags: webserver_phpfpm
    block:

    - name: include php fpm
      include_tasks: phpfpm/main.yml
      when: include_webserver_phpfpm and webserver_phpfpm_pools

  - name: tags-block
    tags: webserver_website
    block:

    - name: include website
      include_tasks: website/main.yml
      when: include_webserver_website

  - name: tags-block
    tags: webserver_appserver
    block:

    - name: include appserver
      include_tasks: appserver/main.yml
      when: include_webserver_appserver

  - name: tags-block
    tags: webserver_mounts
    block:

    - name: include mounts
      include_tasks: mounts/main.yml
      when: include_webserver_mounts
