- block:

  - block:

    - name: include apache2
      include_tasks: apache2/main.yml
      when: include_webserver_apache2

    tags: webserver_apache2

  - block:

    - name: include letsencrypt
      include_tasks: letsencrypt/main.yml
      when: include_webserver_letsencrypt

    tags: webserver_letsencrypt

  - block:

    - name: include php fpm
      include_tasks: phpfpm/main.yml
      when: include_webserver_phpfpm

    tags: webserver_letsencrypt

  tags: webserver
