#- name: find php version
#  package_facts:
#
#- name:
#  set_fact:
#    # find php upstream_version from "epoch:upstream_version+debian_revision", i.e. 2:7.4+76 -> 7.4
#    webserver_php_version: "{{ ansible_facts.packages['php-fpm'].0.version.split(':')[1].split('+')[0] }}"

- name: delete default php-fpm pool
  file:
    path: "/etc/php/{{ webserver_php_version }}/fpm/pool.d/www.conf"
    state: absent

- name: create php-fpm pools
  template:
    src: phpfpm/pool.conf.j2
    dest: '/etc/php/{{ webserver_php_version }}/fpm/pool.d/{{ item.name }}.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  vars:
    name: '{{ item.name }}'
    user: '{{ item.user|default(item.name) }}'
    group: '{{ item.group|default(item.name) }}'
    max_children: "{{ item.max_children|default(5) }}"
    start_servers: "{{ item.start_servers|default(2) }}"
    min_spare_servers: "{{ item.min_spare_servers|default(1) }}"
    max_spare_servers: "{{ item.max_spare_servers|default(3) }}"
    php_options: "{{ item.php_options|default('') }}"
  loop: '{{ webserver_phpfpm_pools }}'
