- name: install goaccess packages
  package:
    pkg:
      - goaccess

- name: deploy goaccess.conf
  copy:
    src: goaccess.conf
    dest: /etc/goaccess/goaccess.conf
    owner: root
    group: root
    mode: 0644

- name: deploy goaccess-last wrapper
  copy:
    src: goaccess-last
    dest: /usr/local/bin/goaccess-last
    owner: root
    group: root
    mode: 0755

- name: create goaccess b-tree database directory
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0700
  loop:
    - /var/lib/goaccess
    - /var/lib/goaccess/global

- name: create website-statistics directories
  file:
    path: /var/www/default/website-statistics/global
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /var/www/default/website-statistics/global
    - /var/www/default/website-statistics/archive

- name: create goaccess cronjob
  template:
    src: '{{ webserver_tls_terminator }}/log/website-statistics.j2'
    dest: /etc/cron.daily/website-statistics
    owner: root
    group: root
    mode: 0755
  when: webserver_stats_generate
