- name: symlink letsencrypt renewal cronjob
  file:
    src: '{{ webserver_letsencrypt_path }}/cron/{{ inventory_hostname }}.cronjob'
    dest: /etc/cron.d/dphys-letsencrypt-acme-tiny-renewal
    state: link
