- name: check if cron exists
  stat:
    path: /etc/cron.d/letsencrypt-acmetiny
  register: webserver_letsencrypt_cronjob

- name: make cron
  make:
    chdir: '{{ webserver_letsencrypt_path }}'
    target: cron
  when: webserver_letsencrypt_cronjob.stat.exists is not defined or not webserver_letsencrypt_cronjob.stat.exists
