- name: create local directories
  file:
    path: '{{ webserver_letsencrypt_path }}/{{ item }}'
    state: directory
  loop:
    - hosts

- name: create hosts file(s)
  template:
    src: letsencrypt/domains.j2
    dest: "{{ webserver_letsencrypt_path }}/hosts/{{ (item.name|default(''.join(['le',index|string]))) }}"
  vars:
    domains: '{{ item.domains }}'
  register: hosts_file
  loop: '{{ webserver_letsencrypt_aliases|flatten(levels=1) }}'
  loop_control:
    index_var: index

- name: make check
  make:
    chdir: '{{ webserver_letsencrypt_path }}'
    target: check
  changed_when: False

- name: make certificate
  make:
    chdir: '{{ webserver_letsencrypt_path }}'
  when: hosts_file.changed
  notify: restart apache2
