- name: create local directories
  file:
    path: '{{ webserver_letsencrypt_path }}/{{ item }}'
    state: directory
  loop:
    - hosts

- name: create hosts file(s)
  template:
    src: letsencrypt/domains.j2
    dest: "{{ webserver_letsencrypt_path }}/hosts/{{ (item.name|default(''.join(['le',index|string]))) }}"
  vars:
    domains: '{{ item.domains }}'
  register: webserver_letsencrypt_hosts_file
  loop: '{{ webserver_letsencrypt_aliases|flatten(levels=1) }}'
  loop_control:
    index_var: index

- name: make permissions
  make:
    chdir: '{{ webserver_letsencrypt_path }}'
    target: permissions
  changed_when: False
  when: webserver_letsencrypt_clone.changed

- name: 'apply permissions on {{ webserver_letsencrypt_path }}'
  file:
    path: '{{ webserver_letsencrypt_path }}'
    state: directory
    owner: letsencrypt
    group: ssl-cert
    mode: '0110'

- name: 'apply permissions on {{ webserver_letsencrypt_path }}/account.key'
  file:
    path: '{{ webserver_letsencrypt_path }}/account.key'
    owner: root
    group: letsencrypt
    mode: '0640'

- name: make check
  make:
    chdir: '{{ webserver_letsencrypt_path }}'
    target: check
  when: webserver_letsencrypt_hosts_file.changed
  changed_when: False

- name: make certificate
  make:
    chdir: '{{ webserver_letsencrypt_path }}'
  when: webserver_letsencrypt_hosts_file.changed
  notify: reload apache2
