- name: tags-block
  block:
  - name: include migrate to ansible
    include_tasks: migrate_to_ansible.yml
    when: webserver_letsencrypt_migrate_to_ansible
  tags: webserver_letsencrypt_migrate_to_ansible

- name: install letsencrypt dependencies
  package:
    pkg:
      - git
      - libwww-perl
      - make
      - ssl-cert
  tags: webserver_letsencrypt_dependencies

- name: create local letsencrypt system group
  group:
    name: letsencrypt
    system: yes

- name: create local letsencrypt system user
  user:
    name: letsencrypt
    home: '{{ webserver_letsencrypt_path }}'
    create_home: no
    shell: /usr/sbin/nologin
    system: yes
    group: letsencrypt
  tags: webserver_letsencrypt_user

- name: 'initialize {{ webserver_letsencrypt_path }} by restoring from backup'
  command: >
    rsync -av -e 'ssh -o StrictHostKeyChecking=no' --usermap=1-999:letsencrypt --groupmap=1-999:ssl-cert
    {{ webserver_letsencrypt_restore_from_backup_path }} {{ webserver_letsencrypt_path }}/
  args:
    creates: '{{ webserver_letsencrypt_path }}/.git'
  notify: 'restart {{ webserver_tls_terminator }}'
  when: webserver_letsencrypt_restore_from_backup
  tags: webserver_letsencrypt_restore_from_backup

- name: 'clone git repo to {{ webserver_letsencrypt_path }}'
  git:
    repo: '{{ webserver_letsencrypt_repo }}'
    dest: '{{ webserver_letsencrypt_path }}'
    accept_hostkey: true
    update: yes
    version: '{{ webserver_letsencrypt_branch }}'
  throttle: 10
  register: webserver_letsencrypt_clone
  tags: webserver_letsencrypt_clone_repo

- name: deploy account.key
  copy:
    dest: '{{ webserver_letsencrypt_path }}/account.key'
    content: '{{ vault_letsencrypt_account_key }}'
    owner: root
    group: letsencrypt
    mode: '0640'
  no_log: true
  when: webserver_letsencrypt_deploy_account_key
  tags: webserver_letsencrypt_deploy_account_key

- name: Toggle Let's Encrypt staging environment ({{ webserver_letsencrypt_use_staging }})
  lineinfile:
    path: '{{ webserver_letsencrypt_path }}/acme.conf'
    create: true
    regexp: '^ACME_DIRECTORY_URL='
    line: 'ACME_DIRECTORY_URL=https://acme-staging-v02.api.letsencrypt.org/directory'
    state: "{{ webserver_letsencrypt_use_staging | ternary('present', 'absent') }}"
    owner: root
    group: letsencrypt
    mode: '0640'
  tags: webserver_letsencrypt_use_staging

- name: tags-block
  block:
  - name: include initialize automatic
    include_tasks: initialize_automatic.yml
    when: not webserver_letsencrypt_initialize_manually
  tags: webserver_letsencrypt_initialize_automatic

- name: tags-block
  block:
  - name: include initialize manually
    include_tasks: initialize_manually.yml
    when: webserver_letsencrypt_initialize_manually
  tags: webserver_letsencrypt_initialize_manually

- import_tasks: cronjob.yml
  tags: webserver_letsencrypt_cronjob
  when: import_webserver_letsencrypt_cronjob
