- name: include authorized keys share data
  include_tasks: authorized_keys_share_data.yml
  loop: "{{ _vhosts | selectattr('type', 'equalto', 'share') | selectattr('name', 'in', _vhostfilter) | list }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.name }}"
