# Enable fail2ban for basic auth login failures.
# This part is so tightly coupled to the webserver role and variables
# that it cannot be part of the fail2ban role.

- name: deploy fail2ban local filter override for apache-auth (<trixie)
  # Manual override as official patch was only released with trixie.
  # https://github.com/fail2ban/fail2ban/issues/3622
  copy:
    src: apache2/fail2ban/apache-common.local
    dest: /etc/fail2ban/filter.d/apache-common.local
    owner: root
    group: root
    mode: "0644"
  notify: reload fail2ban
  when: ansible_facts.distribution_release in ["bullseye", "bookworm"]

- name: remove fail2ban local filter override for apache-auth (>=trixie)
  file:
    dest: /etc/fail2ban/filter.d/apache-common.local
    state: absent
  notify: reload fail2ban
  when: not ansible_facts.distribution_release in ["bullseye", "bookworm"]

- name: deploy fail2ban apache-auth jail config
  template:
    src: apache2/fail2ban/apache-auth.conf.j2
    dest: /etc/fail2ban/jail.d/apache-auth.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload fail2ban

- name: deploy fail2ban bot filters
  copy:
    src: 'apache2/fail2ban/{{ item }}.filter'
    dest: '/etc/fail2ban/filter.d/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  notify: reload fail2ban
  loop:
    - apache-botfail.local
    - apache-botpattern.local
    - apache-botscan.local

- name: deploy fail2ban bot jails
  template:
    src: 'apache2/fail2ban/{{ item }}.jail.j2'
    dest: '/etc/fail2ban/jail.d/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  notify: reload fail2ban
  loop:
    - apache-botfail.conf
    - apache-botpattern.conf
    - apache-botscan.conf
