- name: flush handlers
  meta: flush_handlers

- name: install apache2
  package:
    pkg:
      - apache2

- name: create systemd apache2.service.d directory
  file:
    path: /etc/systemd/system/apache2.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: deploy systemd apache2.service override
  template:
    src: apache2/service/override.conf.j2
    dest: /etc/systemd/system/apache2.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: install php-fpm packages
  package:
    pkg: "{{ webserver_phpfpm_packages }}"
  when: webserver_phpfpm_pools

- name: install webserver-specific packages
  package:
    pkg: "{{ webserver_packages_custom }}"

- name: include suexec
  include_tasks: suexec.yml
  when: "'suexec' in webserver_modules_custom"

- name: include shibboleth
  include_tasks: shibboleth.yml
  when: "'shib' in webserver_modules_custom"

- name: include lastuse fifo
  include_tasks: log_lastuse.yml
  when: webserver_log_lastuse

- name: 'deploy {{ webserver_https_dh_params_size }} bit dh parameters (takes some time)'
  command: 'openssl dhparam -out /etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem {{ webserver_https_dh_params_size }}'
  args:
    creates: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
  notify: restart apache2
  when: webserver_https_dh_params_custom

- name: set custom dh params permissions
  file:
    path: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
    owner: root
    group: ssl-cert
    mode: 0640
  when: webserver_https_dh_params_custom

- name: create directories in /var/www
  file:
    path: '/var/www/{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - empty
    - default

- name: create directories in /var/log/apache2
  file:
    path: '/var/log/apache2/{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - global
    - sites

- name: deploy main server config
  template:
    src: 'apache2/conf/{{ item }}.conf.j2'
    dest: '/etc/apache2/{{ item }}.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
  loop:
    - apache2
    - ports

- name: deploy openssl config
  template:
    src: 'openssl/openssl.cnf.j2'
    dest: '/etc/ssl/openssl.cnf'
    owner: root
    group: root
    mode: 0644
  notify: restart apache2

- name: deploy default server config
  template:
    src: 'apache2/conf/{{ item }}.conf.j2'
    dest: '/etc/apache2/conf-available/{{ item }}.conf'
    owner: root
    group: root
    mode: 0644
  notify: reload apache2
  loop: "{{ webserver_config_default }}"

- name: enable default server config
  file:
    src: '../conf-available/{{ item }}.conf'
    dest: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: link
  notify: reload apache2
  loop: "{{ webserver_config_default }}"

- name: enable custom server config
  file:
    src: '../conf-available/{{ item }}.conf'
    dest: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: link
  notify: reload apache2
  loop: "{{ webserver_config_enable_custom }}"

- name: disable server config
  file:
    path: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: absent
  notify: reload apache2
  loop:
    - security
    - other-vhosts-access-log
    - serve-cgi-bin
    - charset
    - localized-error-pages

- name: disable custom server config
  file:
    path: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: absent
  notify: reload apache2
  loop: "{{ webserver_config_disable_custom }}"

- name: deploy mods-available
  template:
    src: 'apache2/mods/{{ item }}.conf.j2'
    dest: '/etc/apache2/mods-available/{{ item }}.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
  loop:
    - dir
    - ldap
    - status
    - userdir
    - fcgid

- name: enable modules default
  command: 'a2enmod {{ item }}'
  args:
    creates: '/etc/apache2/mods-enabled/{{ item }}.load'
  notify: restart apache2
  loop: '{{ webserver_modules_default }}'

- name: enable modules ldap
  command: 'a2enmod {{ item }}'
  args:
    creates: '/etc/apache2/mods-enabled/{{ item }}.load'
  notify: restart apache2
  loop:
    - authnz_ldap
    - ldap
  when: webserver_ldap

- name: enable modules custom
  command: 'a2enmod {{ item }}'
  args:
    creates: '/etc/apache2/mods-enabled/{{ item }}.load'
  notify: restart apache2
  loop: '{{ webserver_modules_custom }}'

- name: deploy default site content
  template:
    src: 'sites/default.index.html.j2'
    dest: '/var/www/default/index.html'
    owner: root
    group: root
    mode: 0644
  when: webserver_site_deploy_default

- name: deploy webserver logo
  copy:
    src: 'apache2/logo.png'
    dest: '/var/www/default/webserver.png'
    owner: root
    group: root
    mode: 0644
  when: webserver_site_deploy_default

- name: deploy sites-available config - 000-default
  template:
    src: 'apache2/sites/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
    owner: root
    group: root
    mode: 0644
  notify: reload apache2
  when: webserver_site_enable_default

- name: enable sites-enabled config - 000-default
  file:
    src: '../sites-available/000-default.conf'
    dest: '/etc/apache2/sites-enabled/000-default.conf'
    state: link
  notify: reload apache2
  when: webserver_site_enable_default

- name: flush handlers
  meta: flush_handlers

- name: tags-block
  tags: webserver_sites_include
  block:
  - name: include sites-include repo
    include_tasks: sites_include.yml
    when: include_webserver_sites_include

- name: tags-block
  tags:
    - webserver_vhosts
    - webserver_authorized_keys
  block:
  - name: include load authorized keys
    include_tasks: load_authorized_keys.yml
    when: include_webserver_authorized_keys

- name: tags-block
  tags: webserver_vhosts
  block:
  - name: include vhosts
    include_tasks: vhosts.yml
    when: include_webserver_vhosts
    tags:
      - webserver_tmp_vhost_debug_set_fact_performance
      - webserver_tmp_vhost_debug_create_vhosts

- name: deploy apache2 logrotate conf
  template:
    src: apache2/log/apache2.logrotate.j2
    dest: /etc/logrotate.d/apache2
    owner: root
    group: root
    mode: 0644

- name: remove obsolete log files
  file:
    path: /var/log/apache2/other_vhosts_access.log
    state: absent
