- name: flush handlers
  meta: flush_handlers

- name: install apache2
  package:
    pkg:
      - apache2

- name: 'deploy {{ webserver_https_dh_params_size }} bit dh parameters (takes some time)'
  command: 'openssl dhparam -out /etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem {{ webserver_https_dh_params_size }}'
  args:
    creates: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
  when: webserver_https_dh_params_custom

- name: set custom dh params permissions
  file:
    path: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
    owner: root
    group: ssl-cert
    mode: '0640'
  when: webserver_https_dh_params_custom

- name: create /var/www/empty
  file:
    path: /var/www/empty
    state: directory

- name: deploy envvars
  blockinfile:
    path: /etc/apache2/envvars
    block: '{{ webserver_envvars }}'

- name: enable modules
  apache2_module:
    state: present
    name: '{{ item }}'
    ignore_configcheck: True
  notify: restart apache2
  loop:
    - ssl
    - macro
    - env

- name: restart apache
  meta: flush_handlers

- name: deploy conf-available
  template:
    src: 'apache2/{{ item }}.conf.j2'
    dest: '/etc/apache2/conf-available/{{ item }}.conf'
  loop:
    - 000-apache2
    - 001-https
    - 010-well-known
    - 020-macro

- name: enable server config
  file:
    src: '../conf-available/{{ item }}.conf'
    dest: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: link
  notify: reload apache2
  loop:
    - 000-apache2
    - 001-https
    - 010-well-known
    - 020-macro

- name: reload apache
  meta: flush_handlers

- name: create sites-common
  file:
    path: /etc/apache2/sites-common
    state: directory

- name: create sites-common https config
  template:
    src: apache2/https-cert.conf.j2
    dest: '/etc/apache2/sites-common/https-{{ item.name }}.conf'
  vars:
    cert_name: '{{ item.name }}'
  loop: '{{ webserver_letsencrypt_aliases }}'
