- name: flush handlers
  meta: flush_handlers

- name: install apache2
  package:
    pkg:
      - apache2

- name: create systemd apache2.service.d directory
  file:
    path: /etc/systemd/system/apache2.service.d/
    state: directory
  when: webserver_service_start_after_network_online or 'suexec' in webserver_modules_custom

- name: deploy systemd apache2.service override
  template:
    src: apache2/service/override.conf.j2
    dest: /etc/systemd/system/apache2.service.d/override.conf
  notify: reload systemd
  when: webserver_service_start_after_network_online or 'suexec' in webserver_modules_custom

- name: remove systemd apache2.service override
  file:
    path: /etc/systemd/system/apache2.service.d/override.conf
    state: absent
  notify: reload systemd
  when: not (webserver_service_start_after_network_online or 'suexec' in webserver_modules_custom)

- name: install webserver-specific packages
  package:
    pkg: "{{ webserver_extra_packages }}"

- name: include lastuse fifo
  include_tasks: log_lastuse.yml
  when: webserver_log_lastuse

- name: 'deploy {{ webserver_https_dh_params_size }} bit dh parameters (takes some time)'
  command: 'openssl dhparam -out /etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem {{ webserver_https_dh_params_size }}'
  args:
    creates: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
  notify: restart apache2
  when: webserver_https_dh_params_custom

- name: set custom dh params permissions
  file:
    path: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
    owner: root
    group: ssl-cert
    mode: '0640'
  when: webserver_https_dh_params_custom

- name: create directories in /var/www
  file:
    path: '/var/www/{{ item }}'
    state: directory
  loop:
    - empty
    - default

- name: deploy envvars
  blockinfile:
    path: /etc/apache2/envvars
    block: '{{ webserver_envvars }}'
  notify: restart apache2

- name: deploy envvar webshare
  lineinfile:
    path: /etc/apache2/envvars
    line: '{{ webserver_webshare_doc_root }}'
  notify: restart apache2
  when: webserver_webshare

- name: deploy /etc/ssl/certs/id_bd+quovadis.pem
  copy:
    src: apache2/id_bd+quovadis.pem
    dest: /etc/ssl/certs/id_bd+quovadis.pem
  notify: restart apache2
  when: webserver_ldap_ethz

- name: deploy conf-available
  template:
    src: 'apache2/conf/{{ item }}.conf.j2'
    dest: '/etc/apache2/conf-available/{{ item }}.conf'
  notify: reload apache2
  loop:
    - 000-apache2
    - 001-https
    - 002-security
    - 010-well-known
    - 020-macro
    - 021-macro-networks
    - 030-ldap

- name: enable server config
  file:
    src: '../conf-available/{{ item }}.conf'
    dest: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: link
  notify: reload apache2
  loop:
    - 000-apache2
    - 001-https
    - 002-security
    - 010-well-known
    - 020-macro
    - 021-macro-networks
    - 030-ldap

- name: enable custom server config
  file:
    src: '../conf-available/{{ item }}.conf'
    dest: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: link
  notify: reload apache2
  loop: "{{ webserver_config_enable_custom }}"

- name: disable server config
  file:
    path: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: absent
  notify: reload apache2
  loop:
    - security
    - other-vhosts-access-log

- name: disable custom server config
  file:
    path: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: absent
  notify: reload apache2
  loop: "{{ webserver_config_disable_custom }}"

- name: enable modules default
  command: 'a2enmod {{ item }}'
  args:
    creates: '/etc/apache2/mods-enabled/{{ item }}.load'
  notify: restart apache2
  loop: '{{ webserver_modules_default }}'

- name: enable modules ldap
  command: 'a2enmod {{ item }}'
  args:
    creates: '/etc/apache2/mods-enabled/{{ item }}.load'
  notify: restart apache2
  loop:
    - authnz_ldap
    - ldap
  when: webserver_ldap

- name: enable modules custom
  command: 'a2enmod {{ item }}'
  args:
    creates: '/etc/apache2/mods-enabled/{{ item }}.load'
  notify: restart apache2
  loop: '{{ webserver_modules_custom }}'

- name: create sites-common
  file:
    path: /etc/apache2/sites-common
    state: directory

- name: deploy default site content
  template:
    src: 'apache2/sites/default.index.html.j2'
    dest: '/var/www/default/index.html'
  when: webserver_site_deploy_default

- name: deploy sites-available config - 000-default
  template:
    src: 'apache2/sites/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  notify: reload apache2
  when: webserver_site_enable_default

- name: enable sites-enabled config - 000-default
  file:
    src: '../sites-available/000-default.conf'
    dest: '/etc/apache2/sites-enabled/000-default.conf'
    state: link
  notify: reload apache2
  when: webserver_site_enable_default

- name: flush handlers
  meta: flush_handlers
