- name: flush handlers
  meta: flush_handlers

- name: install apache2
  package:
    pkg:
      - apache2

- name: 'deploy {{ webserver_https_dh_params_size }} bit dh parameters (takes some time)'
  command: 'openssl dhparam -out /etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem {{ webserver_https_dh_params_size }}'
  args:
    creates: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
  notify: restart apache2
  when: webserver_https_dh_params_custom

- name: set custom dh params permissions
  file:
    path: '/etc/ssl/private/dhparam_{{ webserver_https_dh_params_size }}.pem'
    owner: root
    group: ssl-cert
    mode: '0640'
  when: webserver_https_dh_params_custom

- name: create /var/www/empty
  file:
    path: /var/www/empty
    state: directory

- name: deploy envvars
  blockinfile:
    path: /etc/apache2/envvars
    block: '{{ webserver_envvars }}'
  notify: restart apache2

- name: deploy envvar webshare
  lineinfile:
    path: /etc/apache2/envvars
    line: '{{ webserver_webshare_doc_root }}'
  notify: restart apache2
  when: webserver_webshare

- name: deploy /etc/ssl/certs/id_bd+quovadis.pem
  copy:
    src: apache2/id_bd+quovadis.pem
    dest: /etc/ssl/certs/id_bd+quovadis.pem
  notify: restart apache2
  when: webserver_ldap_ethz

- name: deploy conf-available
  template:
    src: 'apache2/{{ item }}.conf.j2'
    dest: '/etc/apache2/conf-available/{{ item }}.conf'
  notify: reload apache2
  loop:
    - 000-apache2
    - 001-https
    - 002-security
    - 010-well-known
    - 020-macro
    - 030-ldap

- name: enable server config
  file:
    src: '../conf-available/{{ item }}.conf'
    dest: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: link
  notify: reload apache2
  loop:
    - 000-apache2
    - 001-https
    - 002-security
    - 010-well-known
    - 020-macro
    - 030-ldap

- name: disable server config
  file:
    path: '/etc/apache2/conf-enabled/{{ item }}.conf'
    state: absent
  notify: reload apache2
  loop:
    - security

- name: enable modules default
  apache2_module:
    state: present
    name: '{{ item }}'
    ignore_configcheck: True
  notify: restart apache2
  loop: '{{ webserver_modules_default }}'

- name: enable modules ldap
  apache2_module:
    state: present
    name: '{{ item }}'
    ignore_configcheck: True
  notify: restart apache2
  loop:
    - ldap
    - authnz_ldap
  when: webserver_ldap

- name: enable modules custom
  apache2_module:
    state: present
    name: '{{ item }}'
    ignore_configcheck: True
  notify: restart apache2
  loop: '{{ webserver_modules_custom }}'

- name: flush handlers
  meta: flush_handlers

- name: create sites-common
  file:
    path: /etc/apache2/sites-common
    state: directory

- name: create sites-common https config
  template:
    src: apache2/https-cert.conf.j2
    dest: '/etc/apache2/sites-common/https-{{ item.name }}.conf'
  vars:
    cert_name: '{{ item.name }}'
  loop: '{{ webserver_letsencrypt_aliases }}'
