- name: add gpg key for switchaai repo
  # KeyID 294E37D154156E00FB96D7AA26C3C46915B76742
  copy:
    src: apache2/switchaai.asc
    dest: /etc/apt/trusted.gpg.d/switchaai.asc
    owner: root
    group: root
    mode: 0644

- name: add switchaai repo
  copy:
    dest: /etc/apt/sources.list.d/switchaai.list
    content: "deb http://pkg.switch.ch/switchaai/debian {{ ansible_distribution_release }} main\n"
    owner: root
    group: root
    mode: 0644
  register: switchaai_apt_repo

- name: trigger apt update on repo change
  apt:
    update_cache: yes
  when: switchaai_apt_repo.changed

- name: install shibboleth (switchaai) packages
  package:
    name:
      - shibboleth
      - libapache2-mod-shib

- name: deploy server wide shibboleth (switchaai) conf
  template:
    src: 'apache2/conf/shib.conf.j2'
    dest: '/etc/apache2/conf-available/shib.conf'
    owner: root
    group: root
    mode: 0644
  notify: reload apache2

- name: enable server wide shibboleth (switchaai) conf
  file:
    src: '../conf-available/shib.conf'
    dest: '/etc/apache2/conf-enabled/shib.conf'
    state: link
  notify: reload apache2
