- name: 'clone sites-include repo from {{ webserver_sites_include_repo }}'
  git:
    repo: '{{ webserver_sites_include_repo }}'
    dest: '/etc/apache2/sites-include'
    update: no
  when: webserver_sites_include_repo != ''

- name: create sites-include directory
  file:
    path: /etc/apache2/sites-include
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: webserver_sites_include_repo == ''
