- name: create fcgid directory
  file:
    path: '{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid'
    owner: '{{ vhost_fcgid.name }}'
    group: '{{ vhost_fcgid.name }}'
    mode: '0551'
    state: directory

- name: deploy fcgid wrappers
  copy:
    src: "apache2/fcgid-wrapper-{{ fcgid_type }}"
    dest: "{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type }}"
    owner: "{{ vhost_fcgid.name }}"
    group: "{{ vhost_fcgid.name }}"
    mode: '0550'
  loop: "{{ vhost_fcgid.fcgid }}"
  loop_control:
    loop_var: fcgid_type
    label: "deploy {{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type }}"
