- name: create webshare data structure and permissions
  file:
    path: '{{ vhost.data_path }}/{{ item.path }}'
    owner: '{{ item.owner | default(vhost.name) }}'
    group: '{{ item.group | default(vhost.name) }}'
    mode: "{{ item.mode | default('2770') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - path: '{{ vhost.name }}'
      owner: '{{ vhost.home_perms.owner }}'
      group: '{{ vhost.home_perms.group }}'
      mode: '{{ vhost.home_perms.mode }}'
    - path: '{{ vhost.name }}/logs'
      owner: root
      mode: '0750'
    - path: '{{ vhost.name }}/logs/goaccess'
      owner: root
      mode: '0750'
    - path: '{{ vhost.name }}/logs/goaccess/current'
      owner: root
      mode: '0750'
    - path: '{{ vhost.name }}/private'
    - path: '{{ vhost.name }}/public'
      owner: www-data
      mode: '2570'
    - path: '{{ vhost.name }}/stats'
      owner: www-data
      mode: '0550'
    - path: '{{ vhost.name }}/stats/current'
      owner: www-data
      mode: '0550'
    - path: '{{ vhost.name }}/stats/archive'
      owner: www-data
      mode: '0550'
    - path: '{{ vhost.name }}/tmp'
    #- path: '{{ vhost.name }}/.ssh'
    #  owner: root
    #  mode: '0750'
    #  state: "{{ 'directory' if vhost.authorized_keys else 'absent' }}"
