- name: create fcgid directory
  file:
    path: '{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid'
    owner: '{{ vhost_fcgid.name }}'
    group: '{{ vhost_fcgid.name }}'
    mode: '0551'
    state: directory

- name: deploy custom fcgid wrappers
  template:
    src: "{{ ['apache2/fcgid-wrapper-', fcgid_type, '.j2']|join() if fcgid_type in webserver_fcgid_custom_wrappers else webserver_fcgid_generic_wrapper }}"
    dest: "{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type if fcgid_type in webserver_fcgid_custom_wrappers else 'generic' }}"
    owner: "{{ vhost_fcgid.name }}"
    group: "{{ vhost_fcgid.name }}"
    mode: '0550'
  loop: "{{ vhost_fcgid.fcgid }}"
  when: fcgid_type not in webserver_fcgid_fcgi_extensions
  loop_control:
    loop_var: fcgid_type
    label: "deploy {{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type }}"

- name: deploy generic fcgid wrappers
  copy:
    remote_src: True
    src: "{{ webserver_fcgid_generic_wrapper }}"
    dest: "{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-generic"
    owner: "{{ vhost_fcgid.name }}"
    group: "{{ vhost_fcgid.name }}"
    mode: '0550'
  loop: "{{ vhost_fcgid.fcgid }}"
  when:
    - fcgid_type not in webserver_fcgid_fcgi_extensions
    - fcgid_type in webserver_fcgid_custom_wrappers
  loop_control:
    loop_var: fcgid_type
    label: "deploy {{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type }}"
