- name: deploy default wsgi app
  copy:
    content: '{{ vhost_wsgi.content }}'
    dest: '{{ vhost_wsgi.document_root }}/{{ vhost_wsgi.app }}'
    owner: '{{ vhost_wsgi.owner }}'
    group: '{{ vhost_wsgi.group }}'
    mode: '{{ vhost_wsgi.mode }}'
    force: no

- block:

  - name: remove venv (reinit)
    file:
      path: '{{ vhost_wsgi.document_root }}/{{ vhost_wsgi.venv_path }}'
      state: absent
    when: webserver_wsgi_venv_reinit

  - name: check if venv already exists
    stat:
      path: '{{ vhost_wsgi.document_root }}/{{ vhost_wsgi.venv_path }}'
    register: webserver_wsgi_venv_directory

  - block:

    - name: initialize venv (pip, setuptools, wheel)
      pip:
        name:
          - pip
          - setuptools
          - wheel
        state: latest  # noqa package-latest
        virtualenv: '{{ vhost_wsgi.document_root }}/{{ vhost_wsgi.venv_path }}'
        virtualenv_command: /usr/bin/python3 -m venv
      become: yes
      become_user: "{{ vhost_wsgi.name }}"
      register: webserver_wsgi_venv_initialize

    - name: install requirements
      pip:
        requirements: '{{ vhost_wsgi.document_root }}/{{ vhost_wsgi.venv_requirements }}'
        virtualenv: '{{ vhost_wsgi.document_root }}/{{ vhost_wsgi.venv_path }}'
        virtualenv_command: /usr/bin/python3 -m venv
      become: yes
      become_user: "{{ vhost_wsgi.name }}"
      when: webserver_wsgi_venv_initialize.changed

    when: not webserver_wsgi_venv_directory.stat.exists

  when: vhost_wsgi.venv
