- name: create fcgid directory
  file:
    path: '{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid'
    owner: '{{ vhost_fcgid.name }}'
    group: '{{ vhost_fcgid.name }}'
    mode: '0551'
    state: directory

- name: deploy fcgid generic wrappers
  copy:
    remote_src: True
    src: "{{ webserver_fcgid_generic_wrapper }}"
    dest: "{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-generic"
    owner: "{{ vhost_fcgid.name }}"
    group: "{{ vhost_fcgid.name }}"
    mode: '0550'
  loop: "{{ vhost_fcgid.fcgid.extensions|reject('in', webserver_fcgid_custom_wrappers)|list }}"
  when: fcgid_type not in webserver_fcgid_fcgi_extensions
  loop_control:
    loop_var: fcgid_type
    label: "deploy {{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type }}"

- name: deploy fcgid custom wrappers
  template:
    src: "{{ ['apache2/fcgid/fcgid-wrapper-', fcgid_type, '.j2']|join() }}"
    dest: "{{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type }}"
    owner: "{{ vhost_fcgid.name }}"
    group: "{{ vhost_fcgid.name }}"
    mode: '0550'
  vars:
    options: "{{ vhost_fcgid.fcgid.options[fcgid_type]|default([]) }}"
  loop: "{{ vhost_fcgid.fcgid.extensions|select('in', webserver_fcgid_custom_wrappers)|list }}"
  when: fcgid_type not in webserver_fcgid_fcgi_extensions
  loop_control:
    loop_var: fcgid_type
    label: "deploy {{ vhost_fcgid.data_path }}/{{ vhost_fcgid.name }}/fcgid/fcgid-wrapper-{{ fcgid_type }}"
