- name: set fact _vhosts
  set_fact:
    _vhosts: "{{ _vhosts + [_vhost] }}"
  vars:
    _vhost:
      name: '{{ item.name }}'
      type: "{{ item.type|default('server') }}"
      server_name: '{{ item.server_name }}'
      server_alias: "{{ item.server_alias|default('') }}"
      data_path: "{{ item.data_path|default(webserver_vhost_data_path[item.type|default('server')]) }}"
      document_root: "{{ item.document_root|default([item.data_path|default(webserver_vhost_data_path[item.type|default('server')]), item.name]|join('/')) }}{{ '/public' if item.type|default('server') == 'share' else '' }}"
      http:
        empty: "{{ (item.http|default({})).empty|default(True) }}"
        redirect: "{{ (item.http|default({})).redirect|default(['https', item.server_name]|join(' ')) }}"
        includes: "{{ (item.http|default({})).includes|default([]) }}"
        require: "{{ (item.http|default({})).require|default('grant_share_all') if item.type|default('server') == 'share' else (item.http|default({})).require|default('require_all_granted') }}"
      https:
        cert: "{{ (item.https|default({})).cert|default('') }}"
        empty: "{{ (item.https|default({})).empty|default(True if item.type|default('server') == 'redirect' else False) }}"
        redirect: "{{ (item.https|default({})).redirect|default('' if item.server_alias|default('') == '' else ['https', item.server_name]|join(' ')) }}"
        includes: "{{ (item.https|default({})).includes|default([]) }}"
        require: "{{ (item.https|default({})).require|default('grant_share_all') if item.type|default('server') == 'share' else (item.https|default({})).require|default('require_all_granted') }}"
        fcgid: "{{ (item.https|default({})).fcgid|default([]) }}"
  loop: '{{ webserver_vhosts }}'

- name: debug _vhosts
  debug:
    msg: "{{ _vhosts }}"

- name: include vhosts share data
  include_tasks: vhosts_share_data.yml
  loop: "{{ _vhosts|selectattr('type', 'equalto', 'share')|list }}"
  loop_control:
    loop_var: vhost

- name: set fact _phpfpm_pool_names
  set_fact:
    _phpfpm_pool_names: "{{ webserver_phpfpm_pools|map(attribute='name')|list }}"

- name: debug _phpfpm_pool_names
  debug:
    msg: "{{ _phpfpm_pool_names }}"

- name: create vhosts
  template:
    src: "apache2/sites/vhost.conf.j2"
    dest: '/etc/apache2/sites-available/{{ vhost.name }}.conf'
  notify: reload apache2
#  vars: '{{ item }}'
  vars:
    phpfpm_pool_names: '{{ _phpfpm_pool_names }}'
  loop: '{{ _vhosts }}'
  loop_control:
    loop_var: vhost

- name: set fact _vhosts_fcgid
  set_fact:
    _vhosts_fcgid: "{{ _vhosts_fcgid + [_vhost_fcgid] }}"
  vars:
    _vhost_fcgid:
      name: '{{ item.name }}'
      data_path: '{{ item.data_path }}'
      fcgid: '{{ item.https.fcgid }}'
  loop: "{{ _vhosts|selectattr('https.fcgid')|list }}"

- name: debug _vhosts_fcgid
  debug:
    msg: "{{ _vhosts_fcgid }}"

- name: include fcgid
  include_tasks: vhosts_fcgid.yml
  loop: "{{ _vhosts_fcgid }}"
  loop_control:
    loop_var: vhost_fcgid

- name: enable vhosts
  file:
    src: '../sites-available/{{ vhost.name }}.conf'
    dest: '/etc/apache2/sites-enabled/{{ vhost.name }}.conf'
    state: link
  notify: reload apache2
  loop: '{{ _vhosts }}'
  loop_control:
    loop_var: vhost
